global.DEV_CurDeviceData = {}
global.DEV_CurDeviceMac = ""
global.DEV_ListDeviceMac = []
global.NET_ListDeviceData = []
global.NET_ListBindData = []
global.NET_CurDeviceData = {}
global.PAG_EditDataAnalysis = {}
global.NET_LexemeAnalysis = []
global.MQTT_Client = ""
global.MQTT_Receive = ""
global.NET_LexemeAnalysisWaveID = ""
global.URL_Rroxy = false //true:开代理 false: 不开代理
global.DEVNUM = 0
global.VERSION = "测试版本3.7"//测试版本
// global.VERSION = ""
global.SHOW_Cry = true
global.SHOW_LastCry = false
global.DEV_ListDeviceMacTime = 0
global.NETWORK = true
global.MQTTWORK = true
global.MQTTWORKTime = 0
global.MQTTDATA = {}
global.MQTTSTATUS = 2
